apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-dev
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: eks_dev